blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.views import (
    create_blog_view,
    detail_post_view,
    edit_blog_view,
    like_post_view,
    unlike_post_view,
    show_category_page_view,
    remove_like_post_view,
    remove_unlike_post_view,
    create_comment_view,
    like_comment_view,
    unlike_comment_view,
    remove_like_comment_view,
    remove_unlike_comment_view,
    post_notification,
    delete_post_view,
    all_categories_view,
    edit_request_view,
    show_edit_request_notification_view,
    remove_edit_request_view,
    accept_edit_request_view,
    report_post_view,
    report_comment_view,
)


urlpatterns = [
    path('create_post/', create_blog_view, name='create-post'),
    path('<slug>/', detail_post_view, name='detail-post'),
    path('<slug>/edit/', edit_blog_view, name='edit-post'),
    path('<slug>/delete/', delete_post_view, name='delete-post'),
    path('<slug>/like/', like_post_view, name='like-post'),
    path('<slug>/remove_like/', remove_like_post_view, name='remove-like-post'),
    path('<slug>/unlike/', unlike_post_view, name='unlike-post'),
    path('<slug>/remove_unlike/', remove_unlike_post_view, name='remove-unlike-post'),
    path('<slug>/comment/', create_comment_view, name='create-comment'),
    path("<slug>/<int:comment_id>/comment/like_comment", like_comment_view, name='like-comment'),
    path("<slug>/<int:comment_id>/comment/unlike_comment", unlike_comment_view, name='unlike-comment'),
    path("<slug>/<int:comment_id>/comment/remove_like_comment", remove_like_comment_view, name='remove-like-comment'),
    path("<slug>/<int:comment_id>/comment/remove_unlike_comment", remove_unlike_comment_view, name='remove-unlike-comment'),

    path("show_notification/<int:notification_pk>/<int:post_pk>/", post_notification, name='show-notification'),
    path("show_edit_request_notification/<int:notification_pk>/<edit_request_id>", show_edit_request_notification_view, name='show-edit-request-notification'),

    path('all_categories/', all_categories_view, name='all-categories'),
    path('category/<str:category_name>', show_category_page_view, name='show-category'),

    path('edit_request/<blog_post_id>', edit_request_view, name='edit-request'),
    path('remove_edit_request/<edit_request_id>', remove_edit_request_view, name='remove-edit-request'),
    path('accept_edit_request/<edit_request_id>', accept_edit_request_view, name='accept-edit-request'),

    path('report_post/<to_user_id>/<post_slug>', report_post_view, name='report-post'),
    path('report_comment/<to_user_id>/<comment_id>', report_comment_view, name='report-comment'),

]

    

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    home_page_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('', home_page_view, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from pyexpat import model
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings

from ckeditor.fields import RichTextField


def get_header_image_filepath(self, filename):
    return f'header_images/{self.pk}/{filename}'



class Category(models.Model):
    name                    = models.CharField(max_length=35, unique=True)

    def __str__(self):
        return self.name
    


class BlogPost(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    body                    = RichTextField(blank=True, null=True)
    category                = models.ForeignKey(Category, on_delete=models.CASCADE)
    header_image            = models.ImageField(max_length=255, upload_to=get_header_image_filepath, null=True, blank=True)
    video                   = models.FileField(null=True, blank=True, upload_to="videos/%y")
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name='date published')
    date_updated            = models.DateTimeField(auto_now=True, verbose_name='date updated')
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                    = models.SlugField(blank=True, unique=True)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_post', blank=True, null=True)
    unlikes                 = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlikes_post', blank=True, null=True)
    views                   = models.PositiveIntegerField(default=0)
    number_of_edits         = models.PositiveIntegerField(default=0)

    

    def total_likes(self):
        return self.likes.count()
    
    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return self.title


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)


class Comment(models.Model):
    post                    = models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comment_author', on_delete=models.CASCADE)
    body                    = models.TextField()
    date_added              = models.DateTimeField(auto_now_add=True)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_comment', blank=True)
    unlikes                 = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlikes_comment', blank=True)


    def total_likes(self):
        return self.likes.count()
    
    def total_unlikes(self):
        return self.unlikes.count()

    def __str__(self):
        return f"{self.post.title} - {self.author.username}"
    

class EditRequest(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    body                    = RichTextField(blank=True, null=True)
    category                = models.ForeignKey(Category, on_delete=models.CASCADE)
    header_image            = models.ImageField(max_length=255, upload_to=get_header_image_filepath, null=True, blank=True)
    video                   = models.FileField(null=True, blank=True, upload_to="videos/%y")
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name='date published')
    date_updated            = models.DateTimeField(auto_now=True, verbose_name='date updated')
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='post_owner')
    editor                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='editor')
    post_id                 = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.title + "edit_request"
    

class Notification(models.Model):
    ## 1-Like 2-Comment 3-Edit Request
    notification_type       = models.SmallIntegerField()
    to_user                 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='notification_to', on_delete=models.CASCADE, null=True)
    from_user               = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='notification_from', on_delete=models.CASCADE, null=True)
    post                    = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name="+", blank=True, null=True)
    comment                 = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="+", blank=True, null=True)
    edit                    = models.ForeignKey(EditRequest, on_delete=models.CASCADE, related_name="+", blank=True, null=True)
    date                    = models.DateTimeField(default=timezone.now)
    user_has_seen           = models.BooleanField(default=False)


REPORT_TYPES = [
    ('Slang Word Choice', 'Slang Word Choice'),
    ('Racist Discourse', 'Racist Discourse'),
    ('Wrong Category Selection', 'Wrong Category Selection')
]

class Report(models.Model):
    from_user                   = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='report_from', on_delete=models.CASCADE)
    to_user                     = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='report_to', on_delete=models.CASCADE)
    post                        = models.ForeignKey(BlogPost, related_name='reported_post', on_delete=models.CASCADE, null=True, blank=True)
    comment                     = models.ForeignKey(Comment, related_name='reported_comment', on_delete=models.CASCADE, null=True, blank=True)
    report_type                 = models.CharField(max_length=50, choices=REPORT_TYPES)
    report_date                 = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} -> {self.to_user}'
    







blog/forms.py
from django import forms
from blog.models import BlogPost, Comment, EditRequest, Report

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'category', 'header_image', 'video')



class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'category', 'header_image', 'video')
    
    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if commit:
            blog_post.save()
        
        return blog_post


class CreateCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)


class CreateEditRequestForm(forms.ModelForm):

    class Meta:
        model = EditRequest
        fields = ('title', 'body', 'category', 'header_image', 'video')



class CreateReportForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = ('report_type',)












blog/templates/blog/all_categories.html
{% extends 'base.html' %}

{% block title %}{{category_name}}{% endblock title %}


{% block content %}
<style type="text/css">
  @media (max-width: 768px) {
    .right-column {
      margin-left: 0px;
    }
  }

  @media (min-width: 768px) {
    .right-column {
      margin-left: 20px;
    }
  }

  .blog-post-container {
    background-color: #f2f2f2;
    margin-bottom: 20px;
    width: 100%;
  }

  .create-post-bar {
    background-color: #f2f2f2;
    margin-bottom: 20px;
  }

  .left-column {
    padding: 0px;
  }

  .right-column {
    padding: 0px;
  }
</style>

<div class="container">
  <div class="row">

        <!-- Right 'Create Post' Bar -->
        <div class="create-post-bar d-lg-none col-lg-7 offset-lg-1 text-center">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Create a Post</h5>
                <hr>
                <p class="card-text">Create a post and find out what people think.</p>
                {% if request.user.is_authenticated %}
                <a href="{% url 'create-post' %}" class="btn btn-outline-success">Create Post</a>
                {% else %}
                <a href="{% url 'register' %}" class="btn btn-outline-success">Create Post</a>
                {% endif %}
              </div>
            </div>
          </div>
          <!-- End Right 'Create Post' Bar -->
  
    <!-- Blog Feed -->
    <div class="left-column col-lg-7 offset-lg-1">
      <div class="text-center"><h2>Categories</h2></div>
      {% for category in categories %}

        <a href="{% url 'show-category' category.name %}" class="text-decoration-none text-dark">
          <div class="card m-2">
            <div class="card-body m-2">
             {{category.name}}
            </div>
          </div>
  
        </a>
      {% endfor %}

    </div>
    <!-- End Blog Feed -->


    <!-- Right 'Create Post' Column -->
    <div class="right-column col-lg-3 d-lg-flex d-none flex-column text-center">
        <div class="create-post-bar">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Create a Post</h5>
              <hr>
              <p class="card-text">Create a post and find out what people think.</p>
              {% if request.user.is_authenticated %}
              <a href="{% url 'create-post' %}" class="btn btn-outline-success">Create Post</a>
              {% else %}
              <a href="{% url 'register' %}" class="btn btn-outline-success">Create Post</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <!-- End Right 'Create Post' Column -->


  </div>
</div>




{% endblock content %}












blog/templates/blog/category_page.html
{% extends 'base.html' %}

{% block title %}{{category_name}}{% endblock title %}

{% block content %}
<style type="text/css">
  @media (max-width: 768px) {
    .right-column {
      margin-left: 0px;
    }
  }

  @media (min-width: 768px) {
    .right-column {
      margin-left: 20px;
    }
  }

  .blog-post-container {
    background-color: #f2f2f2;
    margin-bottom: 20px;
    width: 100%;
  }

  .create-post-bar {
    background-color: #f2f2f2;
    margin-bottom: 20px;
  }

  .left-column {
    padding: 0px;
  }

  .right-column {
    padding: 0px;
  }
</style>

<div class="container">
  <div class="row">

    <!-- Right 'Create Post' Bar -->
    <div class="create-post-bar d-lg-none col-lg-7 offset-lg-1 text-center">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Create a Post</h5>
          <hr>
          <p class="card-text">Create a post and find out what people think.</p>
          {% if request.user.is_authenticated %}
          <a href="{% url 'create-post' %}" class="btn btn-outline-success">Create Post</a>
          {% else %}
          <a href="{% url 'register' %}" class="btn btn-outline-success">Create Post</a>
          {% endif %}
        </div>
      </div>
    </div>
    <!-- End Right 'Create Post' Bar -->

    <!-- Blog Feed -->
    <div class="left-column col-lg-7 offset-lg-1">
        {% if posts %}
        {% for post in posts %}
        <div class="blog-post-container">
          {% include 'snippets/blog_post_snippet.html' with blog_post=post %}
        </div>
        {% endfor %}
        {% else %}
        <div class="blog-post-container">
          {% include 'snippets/blog_post_snippet.html' with query=query %}
        </div>
        {% endif %}
  
        <!-- Pagination -->
        {% include 'snippets/blog_post_pagination.html' with posts=posts %}
  
      </div>
      <!-- End Blog Feed -->



    <!-- Right 'Create Post' Column -->
    <div class="right-column col-lg-3 d-lg-flex d-none flex-column text-center">
      <div class="create-post-bar">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Create a Post</h5>
            <hr>
            <p class="card-text">Create a post and find out what people think.</p>
            {% if request.user.is_authenticated %}
            <a href="{% url 'create-post' %}" class="btn btn-outline-success">Create Post</a>
            {% else %}
            <a href="{% url 'register' %}" class="btn btn-outline-success">Create Post</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <!-- End Right 'Create Post' Column -->

  </div>
</div>




{% endblock content %}










blog/templates/blog/create_comment.html
{% extends 'base.html' %}

{% block title %}Leaving a Comment{% endblock title %}

{% block content %}


   <div class="container text-center mt-5">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-lg btn-info">Leave a Comment</button>
    </form>
   </div>


{% endblock content %}

blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Create Post{% endblock title %}

{% block content %}

<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }

    .submit-button {
        max-width: 200px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required
                        autofocus>
                </div>

                <!--Category-->
                <div class="form-group">
                    <label for="id_title">Category</label>
                    {% render_field form.category class="form-control" placeholder="Select Category" %}
                </div>

                <!--Header Image-->
                <div class="form-group">
                    <label for="id_title">Header Image</label>
                    {% render_field form.header_image class="form-control" placeholder="Header Image" %}
                </div>

                <!--Video-->
                <div class="form-group">
                    <label for="id_title">Video</label>
                    {% render_field form.video class="form-control" placeholder="Video" %}
                </div>
                

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Content</label>
                    {% render_field form.body class="form-control" placeholder="This post is about..." %}
                    {{form.media}}
                </div>

                <!-- Submit btn -->
                <div class="d-flex justify-content-center"><button class="submit-button btn btn-lg btn-outline-primary btn-block" type="submit">POST IT</button></div>
            </form>

            
        </div>
    </div>
</div>



{% endblock content %}

blog/templates/blog/detail_post.html
{% extends 'base.html' %}

{% block title %}Post Details{% endblock title %}

{% block content %}
<style type="text/css">
	.card {
		max-width: 700px;
	}

	.container {
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<div class="card-header">
				<div class="row">
					<div class="col"><a href="{% url 'account' user_id=blog_post.author.id %}">{{blog_post.author.username}}</a></div>
					<div class="col">
						{% if not request.user in blog_post.likes.all %}
						<form action="{% url 'like-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-outline-success btn-sm mr-2">Like</button>
						</form>
						{% else %}
						<form action="{% url 'remove-like-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-success btn-sm">Liked</button>
						</form>
						{% endif %}
					</div>
					<div class="col">
						{% if not request.user in blog_post.unlikes.all %}
						<form action="{% url 'unlike-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-outline-danger btn-sm mr-2">Unlike</button>
						</form>
						{% else %}
						<form action="{% url 'remove-unlike-post' blog_post.slug %}" method="POST">
							{% csrf_token %}
							<button type="submit" name="post_id" value="{{blog_post.id}}"
								class="btn btn-danger btn-sm">Unliked</button>
						</form>
						{% endif %}
					</div>
					<div class="col">
						<a href="{% url 'report-post' blog_post.author.id blog_post.slug %}"><button class='btn btn-danger'>REPORT</button></a>
					</div>
				</div>
			</div>
			{% if blog_post.header_image %}
						<img class="card-img-top" src="{{blog_post.header_image.url}}" alt="header_image">
					{% else %}
					{% endif %}
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">{{blog_post.title}}</h2>
				<p class="card-text">
					
					{% if blog_post.video %}
						<video width="360" height="320" controls="controls">
							<source src="{{blog_post.video.url}}" type="video/mp4" />
							Your browser does not support the video tag.
						</video>
					{% endif %}
					<br>
					
					<br>
					{{blog_post.body|safe}}		
				</p>
				{% if blog_post.author == request.user %}
				<a href="{% url 'edit-post' blog_post.slug %}"><button type="button" class="btn btn-outline-dark">Edit
						Post</button></a>
				<a href="{% url 'delete-post' blog_post.slug %}"><button type="button" class="btn btn-outline-danger">Delete Post</button></a>
				{% else %}
				<a href="{% url 'edit-request' blog_post.id %}"><button type="button" class="btn btn-outline-warning">Edit Request</button></a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
				<div class="row d-flex justify-content-between">
					<div class="col">
						Likes: {{likes_count}} | Unlikes: {{unlikes_count}}
					</div>
					<div class="col">Views: {{blog_post.views}}</div>
					<div class="col">Number of Edits: {{blog_post.number_of_edits}}</div>
				</div>
				<hr>
				Last Edit on {{blog_post.date_updated}} by {{blog_post.author.username}}
			</div>
		</div>

	</div>
</div>

<!--Comment Division-->
<div class="container-fluid">
	<div class="container-fluid">
		<h2 class='text-center'>Comments</h2>
		{% if blog_post.comments.all %}
			{% for comment in blog_post.comments.all %}
				<div class="container">
					<div class="card m-auto">
						<div class="card-header">
							<div class="row">
								<div class="row">
									<div class="col"><a href="{% url 'account' user_id=comment.author.id %}">{{comment.author.username}}</a></div>
									<div class="col">
										{% if not request.user in comment.likes.all %}
										<form action="{% url 'like-comment' blog_post.slug comment.id %}" method="POST">
											{% csrf_token %}
											<button type="submit" name="post_id" value="{{blog_post.id}}"
												class="btn btn-outline-success btn-sm mr-2">Like</button>
										</form>
										{% else %}
										<form action="{% url 'remove-like-comment' blog_post.slug comment.id %}" method="POST">
											{% csrf_token %}
											<button type="submit" name="post_id" value="{{blog_post.id}}"
												class="btn btn-success btn-sm">Liked</button>
										</form>
										{% endif %}
									</div>
									<div class="col">
										{% if not request.user in comment.unlikes.all %}
										<form action="{% url 'unlike-comment' blog_post.slug comment.id %}" method="POST">
											{% csrf_token %}
											<button type="submit" name="post_id" value="{{blog_post.id}}"
												class="btn btn-outline-danger btn-sm mr-2">Unlike</button>
										</form>
										{% else %}
										<form action="{% url 'remove-unlike-comment' blog_post.slug comment.id %}" method="POST">
											{% csrf_token %}
											<button type="submit" name="post_id" value="{{blog_post.id}}"
												class="btn btn-danger btn-sm">Unliked</button>
										</form>
										{% endif %}
									</div>
									<div class="col">
										<a href="{% url 'report-comment' comment.author.id comment.id %}"><button class="btn btn-danger">REPORT</button></a>
									</div>
								</div>
							</div>
						</div>
						<div class="card-body">
							{{comment.body}}
						</div>
						<div class="card-footer">
							<div class="row">
								<div class="col">Likes: {{comment.total_likes}} | Unlikes: {{comment.total_unlikes}}</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<div class="container text-center">No Comments Yet. <a href="{% url 'create-comment' blog_post.slug %}"> Add One.</a></div>
		{% endif %}
	</div>
</div>

<div class="container text-center">
	<div class="text-center">
		{% if blog_post.comments.all %}
			<a href="{% url 'create-comment' blog_post.slug %}">Leave a Comment..</a>	
		{% endif %}
	</div>
</div>

{% endblock content %}

blog/templates/blog/edit_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Edit Post{% endblock title %}

{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>
				
				<!--Category-->
                <div class="form-group">
                    <label for="id_title">Category</label>
                    {% render_field form.category class="form-control" placeholder="Select Category" %}
                </div>

                <!--Header Image-->
                <div class="form-group">
                    <label for="id_title">Header Image</label>
                    {% render_field form.header_image class="form-control" placeholder="Header Image" %}
                </div>

                <!--Video-->
                <div class="form-group">
                    <label for="id_title">Video</label>
                    {% render_field form.video class="form-control" placeholder="Video" %}
                </div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					{% render_field form.body class="form-control" placeholder="This blog is about..." %}
					{{form.media}}
				</div>


				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>


{% endblock content %}

blog/templates/blog/edit_request.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Edit Post{% endblock title %}

{% block content %}

<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }

    .submit-button {
        max-width: 200px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required
                        autofocus>
                </div>

                <!--Category-->
                <div class="form-group">
                    <label for="id_title">Category</label>
                    {% render_field form.category class="form-control" placeholder="Select Category" %}
                </div>

                <!--Header Image-->
                <div class="form-group">
                    <label for="id_title">Header Image</label>
                    {% render_field form.header_image class="form-control" placeholder="Header Image" %}
                </div>

                <!--Video-->
                <div class="form-group">
                    <label for="id_title">Video</label>
                    {% render_field form.video class="form-control" placeholder="Video" %}
                </div>
                

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Content</label>
                    {% render_field form.body class="form-control" placeholder="This post is about..." %}
                    {{form.media}}
                </div>

                <!-- Submit btn -->
                <div class="d-flex justify-content-center"><button class="submit-button btn btn-lg btn-outline-primary btn-block" type="submit">SEND EDIT REQUEST</button></div>
            </form>

            
        </div>
    </div>
</div>



{% endblock content %}

blog/templates/blog/report_comment.html
{% extends 'base.html' %}

{% block title %}Report{% endblock title %}

{% block content %}

    <div class="container d-flex justify-content-center">
        <div class="container mt-5">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}

                <button type="submit" class='btn btn-danger'>Report</button>
            </form>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/report_post.html
{% extends 'base.html' %}

{% block title %}Report{% endblock title %}

{% block content %}

    <div class="container d-flex justify-content-center">
        <div class="container mt-5">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}

                <button type="submit" class='btn btn-danger'>Report</button>
            </form>
        </div>
    </div>

{% endblock content %}